version: 0.2
phases:
  pre_build:
    commands:
      - echo "Getting git stuff in to work"
      - curl -s -O -L  https://$GITHUB_TOKEN@raw.githubusercontent.com/sweet-io/devops-tools-and-scripts/master/ci/cd/codebuild-git-wrapper.sh
      - chmod +x codebuild-git-wrapper.sh
      - ./codebuild-git-wrapper.sh $DEPLOY_BRANCH
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - COMMIT_TAG=$(git tag -l --points-at $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=$(if [[ $STAGE == "production" ]]; then echo ""; else echo $STAGE-; fi)$(if [ $COMMIT_TAG ]; then echo $COMMIT_TAG-; else echo ""; fi)${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker login --username sweetio -p $DOCKER_HUB_TOKEN
      - docker pull $ECR_URL:latest || true
      - docker build -t $ECR_URL:latest
        --build-arg github_token="$GITHUB_TOKEN" 
        -f docker/Dockerfile .
      - docker tag $ECR_URL:latest $ECR_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_URL:$IMAGE_TAG
      - docker push $ECR_URL:latest
      - echo Writing image definitions
      - printf '[{"name":"auctionfrontend","imageUri":"%s"}]' "$ECR_URL:$IMAGE_TAG" | tee imagedefinitions.json
artifacts:
  files: imagedefinitions.json
